# frozen_string_literal: true

# This example tests the scenario from issue #46: changing a resolution version
# with multiple platforms in the lockfile should not cause a confusing error.

source "https://rubygems.org"

gem "bundler-resolutions", path: "../../../"
gem "figjam", "1.6.2" # Gem that depends on thor
