ThreadSafety/DirChdir:
  Exclude:
  - 'spec/**/*'
RSpec/IndexedLet:
  Exclude:
  - 'spec/**/*'
RSpec/Output:
  Exclude:
  - 'spec/**/*'
Naming/VariableNumber:
  Exclude:
  - 'spec/**/*'
Style/FetchEnvVar:
  Enabled: false
