# frozen_string_literal: true

# This example will produce lock file without thor at all, as no other gem depends on it.

source "https://rubygems.org"

plugin "bundler-resolutions", path: "../../../"
gem "dememoize", "0.1.0"
