# frozen_string_literal: true

# This example will produce lock file with a thor version of 1.3.1, as it is brought in by figjam.
# thor however will not appear in the `DEPENDENCIES` section, as we are not saying it is a
# dependency of our project.

source "https://rubygems.org"

gem "bundler-resolutions", path: "../../../", install_if: -> { require_relative "../../../lib/bundler/resolutions"; true }
gem "colorize" # No version specified
gem "dememoize", "0.1.0"
gem "figjam", "> 1.5.0"
