# frozen_string_literal: true

# This example starts with a lockfile with thor at 1.3.1, but the yaml has changed to 1.3.0

source "https://rubygems.org"

gem "bundler-resolutions", path: "../../../"
gem "dememoize", "0.1.0"
gem "figjam", "1.6.2" # Gem that depends on thor
