source "https://rubygems.org"

# gem "bundler-resolutions", path: "../", install_if: -> { require Gem::Specification.find_by_name('bundler-resolutions').gem_dir + "/lib/bundler/resolutions"; true }
gem "bundler-resolutions", path: "../", install_if: -> { require_relative "../lib/bundler/resolutions"; true }
gem "rspec-core", "< 3.13.2"
